### ISSUE TITLE
heat map issues 

### ISSUE THREAD

**Issue by RayKramp1** [cafferychen777/ggpicrust2#10]
here is my metadata 
[metadata2.csv](https://github.com/cafferychen777/ggpicrust2/files/11150999/metadata2.csv)

and my ko adundances
[HPabun.csv](https://github.com/cafferychen777/ggpicrust2/files/11151001/HPabun.csv)

code for map:
heatmap_plot <- pathway_heatmap(t(SAUN_matrix), metadata, "CST")
print(heatmap_plot)

what I get 
![image](https://user-images.githubusercontent.com/129691560/229863315-e087a8be-d6a0-400f-ad95-0ae0a9f5cd01.png)

it doesn't have CST and isn't normalized 

what it looks like when I normalize with ggplot:
![image](https://user-images.githubusercontent.com/129691560/229863494-a8864491-e1a7-4334-bde8-fa008dedaa8b.png)

trying to figure out what is happening

**Comment by cafferychen777** [comment]
Hi, based on your description, it seems that you are using an outdated
version of the ggpicrust2 package. The latest version of ggpicrust2
(v1.5.0) has fixed some issues with pathway_heatmap() and allows it to
properly handle categorical metadata and normalization. I would suggest
upgrading to the latest version of ggpicrust2 and retry it.

RayKramp1 ***@***.***>于2023年4月5日 周三00:57写道：
