### ISSUE TITLE
ggpicrust2 no plot!

### ISSUE THREAD

**Issue by luozhy88** [cafferychen777/ggpicrust2#12]
<img width="989" alt="image" src="https://user-images.githubusercontent.com/94740863/230411199-d7374a98-2ea1-438b-b376-82de6738b9d4.png">
no figure is showed,why?

**Comment by cafferychen777** [comment]
伸手党滚

**Comment by cafferychen777** [comment]
烦不烦人啊你，不知道自己的debug啊，讲话也没礼貌，滚！

**Comment by luozhy88** [comment]
自己示例文件都这么多错误，不想解决办法，不知道谁没礼貌

**Comment by cafferychen777** [comment]
你自己配不来环境怪别人是吧。巨婴，什么都要别人教是吧，这么多人都能跑出来，为什么不想想是自己的问题？

luozhy88 ***@***.***>于2023年4月6日 周四23:28写道：

**Comment by luozhy88** [comment]
从你说话可以看出，1 你没有耐心 2你脾气很火爆 3自己出了问题还不让别人说。你这些问题我从头看也能解决，只不过帮助你改善你的包而已

**Comment by cafferychen777** [comment]
你不是一直做伸手党？你有帮助改住一个真正的bug?你自己看的来代码吗？弱智，教程都看不懂

luozhy88 ***@***.***>于2023年4月6日 周四23:52写道：
