### ISSUE TITLE
add a parameter to select top significant pathways

### ISSUE THREAD

**Issue by lixiaopi1985** [cafferychen777/ggpicrust2#13]
Hi Caffery,

Thank you for fixing the bug. 

I have a request for the pathway_errorbar(), is it possible to add a parameter to select top significant pathways or top pathways by other criteria. Because I got a different error when using the wrapper ggpicrust2
```
Error in pathway_errorbar(abundance = abundance, daa_results_df = daa_sub_method_results_df,  : 
  The feature with statistically significance are more than 30, the visualization will be terrible.
 Please use select to reduce the number.
```
I could go step by step using each function, but doing so makes the wrapper lose its convenience and its function in preliminary data exploration, don't you think?

Also is it possible to add parameters in the wrapper to choose or turn on or off the existing visualization methods?

Best regards,

**Comment by cafferychen777** [comment]
Dear Dr. Liu,

Thank you for bringing up this issue with the pathway_errorbar() function.
I agree that it would be helpful to have a parameter to select top
significant pathways or top pathways based on other criteria.

Regarding the error you encountered with the ggpicrust2 wrapper, I
understand that using each function step by step would be less convenient
and lose its function in preliminary data exploration.

As for adding parameters to choose or turn on/off existing visualization
methods in the wrapper, I think it's a great idea and I will consider
implementing it in the future.

However, I must inform you that due to my current workload, which includes
multiple final exams, I may not have the time to make these changes
immediately. I apologize for any inconvenience this may cause.

Thank you again for your valuable feedback, and I will keep you updated on
any progress regarding these changes.

Best regards, Caffery

Xiaoping Li ***@***.***>于2023年4月7日 周五00:17写道：

**Comment by ilksentpc** [comment]
Hello Caffery,

Thank you for ggpicrust2; that is a great tool!

I'm wondering if you have developed a parameter for the pathway_errorbar() to select the top significant pathways?

I have a question about selecting "ko" numbers. I run the code below:

```
metadata <- read_excel("picrustmetadata.xlsx")
kegg_abundance <- ko2kegg_abundance(file = "/Users/ilksen/Documents/PhD/Ilksen_Picrust_bacphyllo/KO_metagenome_out/pred_metagenome_unstrat.tsv")

group <- "genotype"
daa_results_df <-
  pathway_daa(
    abundance = kegg_abundance,
    metadata = metadata,
    group = group,
    p.adjust = "BH",
    daa_method = "ALDEx2",
    select = NULL,
    reference = NULL)
  

daa_sub_method_results_df <-
  daa_results_df[daa_results_df$method == "ALDEx2_Kruskal-Wallace test", ]

daa_annotated_sub_method_results_df <-
  pathway_annotation(pathway = "KO",
                     daa_results_df = daa_sub_method_results_df,
                     ko_to_kegg = TRUE)

Group <- metadata$genotype
pathway_errorbar(abundance = kegg_abundance,
                 daa_results_df = daa_annotated_sub_method_results_df,
                 Group = Group,
                  ko_to_kegg = TRUE,
                 p_values_threshold = 0.05,
                 order = "pathway_class",
                 select = NULL,
                 p_value_bar = TRUE,
                 colors = NULL,
                x_lab = NULL)

Error in pathway_errorbar(abundance = kegg_abundance, daa_results_df = daa_annotated_sub_method_results_df,  : 
  The feature with statistically significance are more than 30, the visualization will be terrible.

 Please use select to reduce the number.
 Now you have "ko00563", "ko05412", "ko03450", "ko00311", "ko00310", "ko00600", "ko04142", "ko04260", "ko00909", "ko00510", "ko05110", "ko04974", "ko00565", "ko00905", "ko05222", "ko00514", "ko05416", "ko05140", "ko00591", "ko04370", "ko00380", "ko05120", "ko04666", "ko05322", "ko00627", "ko04380", "ko00941", "ko00943", "ko01057", "ko01056", "ko05016", "ko04145", "ko00071", "ko00072", "ko05210", "ko00531", "ko04916", "ko00533", "ko00360", "ko00633", "ko04115", "ko00362", "ko00603", "ko04270", "ko00281", "ko00280", "ko00601", "ko05146", "ko05145", "ko05144", "ko00051", "ko00643", "ko00120", "ko00965", "ko05414", "ko04614", "ko05010", "ko05012", "ko05131", "ko02060", "ko03320", "ko04744", "ko00522", "ko04622", "ko00460", "ko04970", "ko04972", "ko00232", "ko00660", "ko04512", "ko05410", "ko00331", "ko04080", "ko04514", "ko00473", "ko04510", "k
> View(daa_annotated_sub_method_results_df)
```


You want us to select the "ko" number from here: however, when I looked at the "daa_annotated_sub_method_results_df" file to choose the most significant ones, I couldn't see a few of them among these "ko" numbers(above). Also  "ko04512" and "ko05410" are here(above), but I couldn't find them inside "the "daa_annotated_sub_method_results_df" file.

What's meant by these numbers' order? Like "ko00563" is most significant one? When I look at its p-value, it is not at the top.
Note: I didn't set a "reference"; I have five different plant groups inside "metadata$genotype" if it matters.

Thank you in advance!
Best regards,
Ilksen
