### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, "pathway_description"......", : replacement has 3 rows, data has 1

### ISSUE THREAD

**Issue by etorres475** [cafferychen777/ggpicrust2#15]
Hi Caffery,

Thanks a lot for this useful package!
I am analyzing some data and keep getting the following error:

<img width="920" alt="Screenshot 2023-04-13 at 6 26 29 PM" src="https://user-images.githubusercontent.com/128504496/231903944-2d151f30-86af-4694-b9f3-b32fe30e1c01.png">

Do you have any suggestions to fix it?

Thanks for your help!

Best wishes,

Eliana

**Comment by etorres475** [comment]
With another dataset I am getting the following:
<img width="970" alt="Screenshot 2023-04-13 at 7 03 58 PM" src="https://user-images.githubusercontent.com/128504496/231908713-7bbbfed0-e28d-4264-a0e5-ac1f2bcdc4d4.png">
<img width="950" alt="Screenshot 2023-04-13 at 7 05 04 PM" src="https://user-images.githubusercontent.com/128504496/231908767-04587f93-0060-4e56-bc06-7732be9a1696.png">
<img width="1198" alt="Screenshot 2023-04-13 at 7 05 36 PM" src="https://user-images.githubusercontent.com/128504496/231908830-067174d9-a9d3-4c9f-b2fd-66ad1ba44a9e.png">

**Comment by cafferychen777** [comment]
Dear Eliana,

Thank you for using the ggpicrust2 package and for reaching out to us for assistance.

Based on the error message you shared, it seems that the pathway_description for the pathway "K04260" is causing the issue. One possible solution is to try using the second workflow provided in the tutorial. This workflow can be faster for debugging issues related to pathway descriptions.

You can try removing it from the analysis by excluding it from the pathway list or by filtering it out of your data. You can learn the following code.
[Jordan.R.zip](https://github.com/cafferychen777/ggpicrust2/files/11229291/Jordan.R.zip)


I hope this helps! Please let me know if you have any further questions or concerns.

Best regards,
Chen YANG

**Comment by etorres475** [comment]
Hi Chen,

Thanks a lot for your quick reply!
It worked!

Best wishes
