### ISSUE TITLE
pathway_annotation issue

### ISSUE THREAD

**Issue by KitHubb** [cafferychen777/ggpicrust2#17]
Thank you for the nice package! 
However, when I did `pathway_annotation()`, data loss occurred. 
When I subset about 242 KO  data into 80 lines and divided them into 3 pieces of data, then ran the `pathway_annotation()`.

My data is in the link below.
[mydata](https://drive.google.com/file/d/1WgkCs8PLcFgkoguyGn1j9x-rpkfKjVks/view?usp=sharing)

```
f1 <- ko_daa_sub_method_results_df[1:80, ] # 121
f2 <- ko_daa_sub_method_results_df[81:161, ] # 121
f3 <- ko_daa_sub_method_results_df[162:242, ] # 121

d1 <-pathway_annotation(pathway = "KO",daa_results_df = f1, ko_to_kegg = TRUE) # 53 × 11
d2 <-pathway_annotation(pathway = "KO",daa_results_df = f2, ko_to_kegg = TRUE) # 58 × 11
d3 <-pathway_annotation(pathway = "KO",daa_results_df = f3, ko_to_kegg = TRUE) # 50 × 11
annotation <- rbind(d1, d2, d3)
dim(annotation) # 161
```
The result left only 161 rows out of 242 KO data. 
output is here [result](https://drive.google.com/file/d/1ygGMgPadM99fuReHVphgzZQgRW53M4Hl/view?usp=sharing)

I thought it was a problem with `keggGet()`, so I took the contents inside the `pathway_annotation()`and ran it separately. 

```

ko_id <- ko_daa_sub_method_results_df$feature # 242
pathway_table <-  data.frame(row.names = ko_id)


KeggGet_results <- list()
for ( i in ko_id) {
  KeggGet_results[[i]] <- tryCatch(keggGet(i), error=function(e) NULL) # https://www.biostars.org/p/366463/
}

ko_result_id <- KeggGet_results %>% names # 236

for (i in ko_result_id){
        pathway_table[i, "Level1"]         <- strsplit( KeggGet_results[[i]][[1]]$CLASS, "; ")[[1]][1]
        pathway_table[i, "Level2"]         <- strsplit( KeggGet_results[[i]][[1]]$CLASS, "; ")[[1]][2]
        pathway_table[i, "Level3"]         <-  KeggGet_results[[i]][[1]]$PATHWAY_MAP
        if ( !is.null(KeggGet_results[[i]][[1]]$DESCRIPTION)) {
          pathway_table[i, "pathway_description"] <-  KeggGet_results[[i]][[1]]$DESCRIPTION
          }
}
```
The following message appeared.

_

> Error in `[<-.data.frame`(`*tmp*`, i, "pathway_description", value = c("Type I diabetes mellitus is a disease that results from autoimmune destruction of the insulin-producing beta-cells. Certain beta-cell proteins act as autoantigens after being processed by antigen-presenting cell (APC), such as macrophages and dendritic cells, and presented in a complex with MHC-II molecules on the surface of the APC. Then immunogenic signals from APC activate CD4+ T cells, predominantly of the Th1 subset. Antigen-activated Th1 cells produce IL-2 and IFNgamma. They activate macrophages and cytotoxic CD8+ T cells, and these effector cells may kill islet beta-cells by one or both of two types of mechanisms: (1) direct interactions of antigen-specific cytotoxic T cells with a beta-cell autoantigen-MHC-I complex on the beta-cell, and (2) non-specific inflammatory mediators, such as free radicals/oxidants and cytokines (IL-1, TNFalpha, TNFbeta, IFNgamma).", :
> replacement has 2 rows, data has 1

_

The error did not appear because I excluded the DESCRIPTION column.
```
for (i in ko_result_id){
        pathway_table[i, "Level1"]         <- strsplit( KeggGet_results[[i]][[1]]$CLASS, "; ")[[1]][1]
        pathway_table[i, "Level2"]         <- strsplit( KeggGet_results[[i]][[1]]$CLASS, "; ")[[1]][2]
        pathway_table[i, "Level3"]         <-  KeggGet_results[[i]][[1]]$PATHWAY_MAP
        # if ( !is.null(KeggGet_results[[i]][[1]]$DESCRIPTION)) {
        #   pathway_table[i, "pathway_description"] <-  KeggGet_results[[i]][[1]]$DESCRIPTION
        #   }
}
```
Is there any way to get rid of these loss of data in ggpicrust as well?
I will be grateful if you answer.

**Comment by cafferychen777** [comment]
Dear KitHubb,

Thank you for reaching out to me. I confirm that using the split function to separate large tables and annotations is a correct approach. As for the error you encountered in the [<-.data.frame()] function, it seems that the replacement has two rows, but the data has only one. To solve this problem, you can try excluding the "ko04910" pathway from the table, as shown in the code in the appendix.

Regarding the data loss issue you faced while using the ggpicrust package, it is possible that the root cause lies in the limitations of the kegg database API. In order to address this issue, I suggest that you divide the table into smaller sub-tables, set up a loop, and take breaks between annotations to avoid overwhelming the API. Please refer to the code in the appendix for an example of how to implement this approach.
[Jordan.R.zip](https://github.com/cafferychen777/ggpicrust2/files/11247986/Jordan.R.zip)

I hope this information is helpful to you. Please let me know if you have any further questions or concerns.

Best regards,
Chen YANG

**Comment by cafferychen777** [comment]
Another possible reason for the discrepancy between the input and output rows could be related to API restrictions. To address this issue, I have implemented a code that only annotates pathways with a p.adjust value less than 0.05 for the daa_results_df. As a result, the number of input and output rows might differ.

**Comment by cafferychen777** [comment]
In addition to the previous information, I wanted to let you know that I have updated the package to the latest version 1.6.1. This new version should have resolved the issue of Error in [<-.data.frame(*tmp*, i, "pathway_description". Please let me know if you encounter any further issues or have any additional questions.

**Comment by cafferychen777** [comment]
You're welcome!

I'm glad to hear that my R package could be helpful to you. As a developer,
my goal is to create practical and friendly tools for more people to easily
conduct data analysis and visualization.

Please feel free to provide valuable feedback and suggestions during use. I
will listen carefully and work hard to improve and make this package more
handy and powerful. If you encounter any problems in actual use, please
also let me know. I will fix bugs as soon as possible or update the
documentation.

Finally, I wish you can find more interesting topics and make more
eye-opening discoveries in your future work and study! The stage of
progress is full of surprises and excitement. I believe that as long as you
keep working hard and stay curious, you will continue to achieve success.

Thank you again for using and feedback! I will continue to improve and work
hard to live up to the support and trust of every user.



KitHubb ***@***.***> 于2023年4月18日周二 10:00写道：
