### ISSUE TITLE
Error: Index out of bounds

### ISSUE THREAD

**Issue by RayKramp1** [cafferychen777/ggpicrust2#18]
Group <-metadata1$CST # column which you are interested in metadata

daa_results_list <-
  pathway_errorbar(
    abundance = kegg_abundance,
    daa_results_df = daa_results_pt3,
    Group = Group,
    p_values_threshold = 0.05,
    order = "pathway_class",
    select = NULL,
    ko_to_kegg = FALSE,
    p_value_bar = TRUE,
    colors = NULL,
    x_lab = "pathway_name")
Error: Index out of bounds
[daa_miscpt3.CSV](https://github.com/cafferychen777/ggpicrust2/files/11314100/daa_miscpt3.CSV)
[metadataU.txt](https://github.
[kegg_abundance.csv](https://github.com/cafferychen777/ggpicrust2/files/11314108/kegg_abundance.csv)
com/cafferychen777/ggpicrust2/files/11314101/metadataU.txt)

Cannot visualize any data

**Comment by cafferychen777** [comment]
Hello @RayKramp1 ,
Thank you for your using. May you can try the code as follows:

```
daa_miscpt3 <- read.csv("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/RayKramp1/daa_miscpt3.csv")
kegg_abundance <- read.csv("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/RayKramp1/kegg_abundance.csv", row.names=1)
metadata2 <- read.csv("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/RayKramp1/metadata2.csv")
library(ggpicrust2)
library(patchwork)
library(ggprism)
daa_results_list <-
  pathway_errorbar(
    abundance = kegg_abundance,
    daa_results_df = daa_miscpt3,
    Group = metadata2$CST,
    p_values_threshold = 0.05,
    order = "pathway_class",
    select = NULL,
    ko_to_kegg = TRUE,
    p_value_bar = FALSE,
    colors = NULL,
    x_lab = "pathway_name")
```
[Rplot1.pdf](https://github.com/cafferychen777/ggpicrust2/files/11315844/Rplot1.pdf)
[Rplot2.pdf](https://github.com/cafferychen777/ggpicrust2/files/11315845/Rplot2.pdf)

**Comment by cafferychen777** [comment]
<img width="1267" alt="截屏2023-04-25 10 25 36" src="https://user-images.githubusercontent.com/82987086/234159306-99bd776e-d02b-4900-b1ad-6ff8595d28f2.png">

**Comment by RayKramp1** [comment]
Hello I did everything the same
daa_miscpt3 <- read.csv("/Users/rachaelkramp/Desktop/Selection_paper/Picrust2_analysis/daa_miscpt3.csv")
kegg_abundance <- read.csv("/Users/rachaelkramp/Desktop/Selection_paper/Picrust2_analysis/kegg_abundance.csv", row.names=1)
metadata2 <- read.csv("/Users/rachaelkramp/Desktop/Selection_paper/Picrust2_analysis/metadata.csv")
library(ggpicrust2)
library(patchwork)
library(ggprism)
daa_results_list <-
  pathway_errorbar(
    abundance = kegg_abundance,
    daa_results_df = daa_miscpt3,
    Group = metadata2$CST,
    p_values_threshold = 0.05,
    order = "pathway_class",
    select = NULL,
    ko_to_kegg = TRUE,
    p_value_bar = FALSE,
    colors = NULL,
    x_lab = "pathway_name")
But I am still getting the same error

**Comment by RayKramp1** [comment]
Hello! I figured it out! The metadata and Kegg abundance have to be in the EXACT same order.
