### ISSUE TITLE
pathway_heatmap not returning as expected

### ISSUE THREAD

**Issue by hharder1** [cafferychen777/ggpicrust2#21]
I ran the following code

```{r}
pathway_heatmap(t(abundance_matrix), metadata, "Txt")
```

with these files. 

[metadata.txt](https://github.com/cafferychen777/ggpicrust2/files/11337107/metadata.txt)
[abundance_matrix.csv](https://github.com/cafferychen777/ggpicrust2/files/11337111/abundance_matrix.csv)

I then got something that looks like this:

![image](https://user-images.githubusercontent.com/131917649/234699291-da4135d5-65b8-4f9b-b33e-fa3aaeb33a2f.png)

Even ignoring the crazy size, it looks like all the cells of the heatmap are approximately the same color, so there's no range represented. I know that there are significant differences between my VEH and MOR level of the Txt group (see below).

![image](https://user-images.githubusercontent.com/131917649/234699854-3600318f-6844-4d38-bc2d-3faa8c5d260d.png)

What is going on?

**Comment by cafferychen777** [comment]
Hi,

Based on the images you've shared, it seems like there might be an issue with the code you ran. It appears that all the cells in the heatmap are approximately the same color, indicating that there's no range represented.

It's possible that you haven't set the sample.id in the metadata to be the sample_name, which could be causing this problem. I would suggest checking that to see if it helps.

```
library(ggpicrust2)
library(tidyverse)
abundance_matrix <- read.csv("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/hharder1/abundance_matrix.csv", sep="")
metadata <- read.delim("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/hharder1/metadata.txt")
metadata$sample_name <- metadata$sample.id
rownames(abundance_matrix) <- metadata$sample.id
abundance_matrix <- t(abundance_matrix)
ggpicrust2::pathway_heatmap(abundance_matrix, metadata, "Txt")
```
<img width="290" alt="截屏2023-04-27 14 35 44" src="https://user-images.githubusercontent.com/82987086/234779374-3210c7d0-9184-4333-a467-07064535b985.png">

However, I don't think it's a good idea to directly plot a heatmap for such a large matrix. Instead, you may want to focus on only plotting the pathways that have statistical significance in the pathway analysis, or you can identify the pathways that you are interested in and plot only those.

I hope this helps. Let me know if you have any further questions.

Best regards,
Chen YANG

**Comment by cafferychen777** [comment]
```
library(ggpicrust2)
library(tidyverse)
abundance_matrix <- read.csv("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/hharder1/abundance_matrix.csv", sep="")
metadata <- read.delim("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/hharder1/metadata.txt")
metadata$sample_name <- metadata$sample.id
rownames(abundance_matrix) <- metadata$sample.id
daa_results_df <- pathway_daa(...)
abundance_matrix_sub <-  abundance_matrix[colnames(abundance_matrix) %in% daa_results_df[daa_results_df$p.adjust <= 0.05,]$feature, ]
abundance_matrix_sub <- t(abundance_matrix_sub)
ggpicrust2::pathway_heatmap(abundance_matrix_sub, metadata, "Txt")
```

**Comment by cafferychen777** [comment]
Hello @Nathanielhubert ,

Adding a color label to the bottom of heatmap is a beta function. It can't work stablely so I am still modifing it. I would release the new version with the renewed heatmap. Now you can use image editing software such as Photoshop or Illustrator to add labels to the heatmap.

Best regards,
Chen YANG

**Comment by Nathanielhubert** [comment]
Thank you, Chen Yang,

I was able to get labels using the code below, but it is difficult to be sure the labels are correctly aligned with the data in part because the heatmap is plotting z-scores and I have a table of kegg_abundance.

In hopes of ensuring the correct order of data, I put my metadata and kegg_abundance tables in the same order that I wanted the heatmap plot to show (I was finding the order of the labels may not align correctly if you try re-sorting in R).

Is it possible to plot the abundance data (or log abundance or log relative abundance, whatever is most appropriate) rather than z-score? 

I am also running into a scale issue with the z-score legend as the legend only labels values 0.2, 0.4, 0.6, 0.8 which is a very narrow range, smushed together in the middle of the minimum and maximum values. Is there any way to fix that? Is z-score the most appropriate value to be plotting?

Thank you again for your help! Nate

`library(readr)
library(ggpicrust2)
library(tidyverse)
library(patchwork)
library(ggprism)
library(dplyr)

#   kegg_abundance <- ko2kegg_abundance(file = "pred_metagenome_unstrat.tsv")

metadata <-
  read_delim(
"metadata.txt",
    delim = "\t",
    escape_double = FALSE,
    trim_ws = TRUE
  )

metadata2 <- as.data.frame(metadata) %>%
  rename(sample_name = `sample_name`)

group <-
  "pre_post_intervention" 

# # Create a heatmap
heatmap_plot <- pathway_heatmap(t(kegg_abundance), metadata2, "pre_post_intervention")

heatmap_plot <- heatmap_plot +
  scale_x_discrete(labels = rownames(kegg_abundance)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(heatmap_plot)

ggsave("picrust_heatmap.pdf", plot = heatmap_plot, width = 10, height = 40)`

[picrust_heatmap.pdf](https://github.com/cafferychen777/ggpicrust2/files/11512870/picrust_heatmap.pdf)

**Comment by cafferychen777** [comment]
Hello @Nathanielhubert ,

You can achieve the desired result by using the following code:

```{r}
library(readr)
library(ggpicrust2)
library(tidyverse)
library(patchwork)
library(ggprism)

# Update to the latest version
devtools::install_github("cafferychen777/ggpicrust2")

daa_Welchs_results_0001_df_annotated <- read.delim("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/Nathanielhubert/daa_Welchs_results_0001_df_annotated.txt")

kegg_abundance <- read.delim("~/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/Nathanielhubert/kegg_abundance.txt", row.names = 1)

metadata <- read_delim("Nathanielhubert/QIIME_map_comp4_prePostOnly.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE)

daa_Welchs_results_0001_df_annotated$p_adjust <- round(daa_Welchs_results_0001_df_annotated$p_adjust, 5)

daa_Welchs_results_0001_df_annotated <- daa_Welchs_results_0001_df_annotated[!is.na(daa_Welchs_results_0001_df_annotated$pathway_name),]

p <- pathway_errorbar(
  abundance = kegg_abundance,
  daa_results_df = daa_Welchs_results_0001_df_annotated,
  Group = metadata$pre_post_intervention,
  p_values_threshold = 0.0001,
  order = "pathway_class",
  select = NULL,
  ko_to_kegg = TRUE,
  p_value_bar = TRUE,
  colors = NULL,
  x_lab = "pathway_name"
)

metadata2 <- metadata %>% rename(sample_name = `#SampleID`)

group <- "pre_post_intervention"

# Create a heatmap
heatmap_plot <- ggpicrust2::pathway_heatmap(abundance = kegg_abundance, metadata = metadata2, group = "pre_post_intervention")

heatmap_plot <- heatmap_plot +
  scale_x_discrete(labels = levels(heatmap_plot$data$Sample)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

print(heatmap_plot)

ggsave("picrust_heatmap.pdf", plot = heatmap_plot, width = 10, height = 40)
```

Please make sure to update to the latest version by running the following command before executing the code:

```{r}
devtools::install_github("cafferychen777/ggpicrust2")
```
```
[picrust_heatmap.pdf](https://github.com/cafferychen777/ggpicrust2/files/11516252/picrust_heatmap.pdf)

Feel free to modify the code as per your requirements. Let me know if you need any further assistance!
<img width="1391" alt="截屏2023-05-19 19 12 51" src="https://github.com/cafferychen777/ggpicrust2/assets/82987086/fc27cb40-430b-46da-890b-68a3ee146191">

**Comment by Nathanielhubert** [comment]
Hi again, If you look at the two attached heatmaps here, the z-score patterns are the same but the order of the samples is different - labels must be wrong in one of them. Is there a way to know the labels are right? Do you have to plot z-score or can you plot the abundance patterns?


[picrust_heatmap 4.18.21 PM.pdf](https://github.com/cafferychen777/ggpicrust2/files/11520593/picrust_heatmap.4.18.21.PM.pdf)
[picrust_heatmap_pre_next_to_post.pdf](https://github.com/cafferychen777/ggpicrust2/files/11520596/picrust_heatmap_pre_next_to_post.pdf)

**Comment by Nathanielhubert** [comment]
![Screen Shot 2023-05-19 at 6 23 18 PM](https://github.com/cafferychen777/ggpicrust2/assets/96305121/38f82c34-1b76-4ba9-9add-32dad6d030e1)

Also, the legend is not very informative

**Comment by cafferychen777** [comment]
If you are using heatmap_plot +
  scale_x_discrete(labels = levels(heatmap_plot$data$Sample)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)), the plot will be right. Because the levels(heatmap_plot$data$Sample determine the order of x axis of heatmap.

**Comment by cafferychen777** [comment]
The code inside pathway_heatmap automatically attaches same group level together.

**Comment by cafferychen777** [comment]
<img width="1204" alt="Screenshot 2023-06-03 at 09 26 01" src="https://github.com/cafferychen777/ggpicrust2/assets/82987086/3269a299-144d-4bc3-9e36-d2e5b51cbd66">


<img width="1198" alt="Screenshot 2023-06-03 at 09 20 57" src="https://github.com/cafferychen777/ggpicrust2/assets/82987086/ec93f866-c892-4a76-90b9-38e5ae0b84dd">

Hello @Nathanielhubert ,

I just update ggpicrust2 and I think the new function will help you. Now you don't need to add a label manually.

```
# # Create a heatmap
heatmap_plot <- pathway_heatmap(abundance = kegg_abundance[daa_Welchs_results_0001_df_annotated$feature,], metadata = metadata2, group = "pre_post_intervention")

pathway_heatmap(abundance = kegg_abundance %>% rownames_to_column("feature") %>% right_join(daa_Welchs_results_0001_df_annotated %>% select(all_of(c("feature","pathway_name"))), by = "feature") %>% column_to_rownames("pathway_name") %>% select(-all_of("feature")), metadata = metadata2, group = "pre_post_intervention")
```

Best Regards，
