### ISSUE TITLE
Tiny bug in ggpicrust2 function?

### ISSUE THREAD

**Issue by schuettl** [cafferychen777/ggpicrust2#3]
Hi there,
thanks a lot for providing this nice package.
I think, I found a tiny bug in the ggpicrust2 function:

In line 80 (of ggpicrust2.R) it reads
`if (select == "NULL"){`
which gives the error "Error in if (select == "NULL") { : argument is of length zero"
shouldn't it be
`if (is.null(select)){` ?

**Comment by cafferychen777** [comment]
Hello @schuettl ,

I have upgrade the version, you can use the following code to get latest version.
```
# install.packages("devtools")
devtools::install_github("cafferychen777/ggpicrust2")
```

**Comment by schuettl** [comment]
Perfect, thanks!
