### ISSUE TITLE
ggpicrust2 error in levels

### ISSUE THREAD

**Issue by Lacona** [cafferychen777/ggpicrust2#34]
```
Creating pathway error bar plots...
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [3] is duplicated
 ```

when running
```
results_file <- ggpicrust2(file = abundance_file,
                                 metadata = metadata,
                                 group = "treatment", 
                                 pathway = "KO",
                                 daa_method = "LinDA",
                                 ko_to_kegg = TRUE,
                                 order = "pathway_class",
                                 p_values_bar = TRUE,
                                 x_lab = "pathway_name",
                                reference = "C")
```
My metadata consists of a column "treatment" with 6 different levels. `levels(metadata$treatment) NULL` . Same error occurs after applying levels. `metadata$treatment <- factor(metadata$treatment, levels=c("A", "B", "C", "D", "E", "F"))`
I can run ggpicrust2 with reference "A" and "B" without any issues and I can run it with another dataset with similar metadata structure without any issues. 
Could you please help me fix this error?
Thank you!

**Comment by cafferychen777** [comment]
Hello,

Thank you for bringing this issue to my attention. In order to troubleshoot this problem effectively, I would need a bit more context. Could you possibly provide the dataset you are working with? This would allow me to replicate the issue on my end and hopefully identify a solution more swiftly.

Just to remind you, if your dataset contains sensitive or private information, please make sure to anonymize or de-identify it before sharing.

Thank you for your cooperation and patience while we work to resolve this issue.

Best regards.

**Comment by cafferychen777** [comment]
Dear @Lacona ,

Thank you for reaching out regarding the error you encountered while creating pathway error bar plots using ggpicrust2.

I noticed that you're using the "LinDA" method in your code. When dealing with multiple groups in the metadata, I recommend switching to the "ALDEx2" method for creating pathway error bar plots. From my experience, LinDA can sometimes fail to produce accurate visualizations in cases of comparisons involving multiple groups. 

Please try modifying your code as follows:

```R
results_file <- ggpicrust2(file = abundance_file,
                           metadata = metadata,
                           group = "treatment", 
                           pathway = "KO",
                           daa_method = "ALDEx2",
                           ko_to_kegg = TRUE,
                           order = "pathway_class",
                           p_values_bar = TRUE,
                           x_lab = "pathway_name")
```

Please let me know if this resolves the issue or if you have any further questions. 

Best regards,

Chen

**Comment by Lacona** [comment]
Hello Chen,

thank you for getting back to me so quickly.
I needed some time to try ALDEx2. Unfortunately I can't figure out how to do multiple group comparisons with the ALDEx2 method. Is there any way? The $results don't show them.

Thank you,
Andrea

________________________________
Von: Caffery Yang ***@***.***>
Gesendet: Dienstag, 20. Juni 2023 06:33
An: cafferychen777/ggpicrust2 ***@***.***>
Cc: Andrea Pietruska ***@***.***>; Mention ***@***.***>
Betreff: [EXT] Re: [cafferychen777/ggpicrust2] ggpicrust2 error in levels (Issue #34)

CAUTION: Email Originated Outside of Auburn.

Dear @Lacona<https://github.com/Lacona> ,

Thank you for reaching out regarding the error you encountered while creating pathway error bar plots using ggpicrust2.

I noticed that you're using the "LinDA" method in your code. When dealing with multiple groups in the metadata, I recommend switching to the "ALDEx2" method for creating pathway error bar plots. From my experience, LinDA can sometimes fail to produce accurate visualizations in cases of comparisons involving multiple groups.

Please try modifying your code as follows:

results_file <- ggpicrust2(file = abundance_file,
                           metadata = metadata,
                           group = "treatment",
                           pathway = "KO",
                           daa_method = "ALDEx2",
                           ko_to_kegg = TRUE,
                           order = "pathway_class",
                           p_values_bar = TRUE,
                           x_lab = "pathway_name")

Please let me know if this resolves the issue or if you have any further questions.

Best regards,

Chen

**Comment by cafferychen777** [comment]
@Lacona 

Dear Andrea,

Thank you for reaching out and for your patience. I understand that you have been exploring the ALDEx2 method and are having trouble figuring out how to perform multiple group comparisons. Unfortunately, the `$results` output does not provide the desired information.

To address this issue, you can try the following code snippet:

```R
library(readr)
library(ggpicrust2)
library(tibble)
library(tidyverse)
library(ggprism)
library(patchwork)

# Load metadata as a tibble
metadata <- read_delim("/Users/apple/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/Lacona/Salmonella22_metadata_42R.tsv", delim = "\t", escape_double = FALSE, trim_ws = TRUE) 

# Load KEGG pathway abundance
kegg_abundance <- ko2kegg_abundance("/Users/apple/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/Lacona/pred_metagenome_unstrat (2).tsv") 

# Perform pathway differential abundance analysis (DAA) using ALDEx2 method
daa_results_df <- pathway_daa(abundance = kegg_abundance, metadata = metadata, group = "treatment", daa_method = "ALDEx2", select = NULL, reference = NULL) 

# Filter results for ALDEx2_Welch's t-test method
daa_sub_method_results_df <- daa_results_df[daa_results_df$method == "ALDEx2_Kruskal-Wallace test", ]

# Annotate pathway results using KO to KEGG conversion
daa_annotated_sub_method_results_df <- pathway_annotation(pathway = "KO", daa_results_df = daa_sub_method_results_df, ko_to_kegg = TRUE)

# Generate pathway error bar plot
pathway_errorbar(abundance = kegg_abundance, daa_results_df = daa_annotated_sub_method_results_df %>%
                        filter(!is.na(pathway_class)), Group = metadata$treatment, p_values_threshold = 0.05, order = "pathway_class", select = c("ko00561", "ko00310", "ko00604", "ko04973", "ko01051", "ko00300", "ko00591", "ko00253", "ko00380", "ko00625", "ko00627", "ko00270", "ko00941", "ko04910", "ko00363", "ko02010", "ko00361", "ko00362", "ko01040", "ko04626", "ko05020", "ko05146", "ko00051"), ko_to_kegg = TRUE, p_value_bar = FALSE, colors = NULL, x_lab = "pathway_name")

# Perform pathway PCA
pathway_pca(abundance = kegg_abundance, metadata = metadata, group = "treatment")

# Filter features with p-value < 0.05
feature_with_p_0.05 <- daa_annotated_sub_method_results_df %>% filter(p_adjust < 0.05) %>% filter(!is.na(pathway_class))

# Generate pathway heatmap
pathway_heatmap(abundance = kegg_abundance %>% filter(rownames(.) %in% feature_with_p_0.05$feature) %>% rownames_to_column("feature") %>% left_join(daa_annotated_sub_method_results_df %>% select(all_of(c("feature","pathway_name"))), by

 = "feature") %>% column_to_rownames("pathway_name") %>% select(-"feature"), metadata = metadata, group = "treatment")
```

Please ensure that you modify the file paths in the code snippet to match your actual data file locations. This code will help you perform multiple group comparisons using the ALDEx2 method and generate pathway error bar plots, pathway PCA plots, and pathway heatmaps based on your metadata and KEGG abundance data.

If you have any further questions or need additional assistance, please don't hesitate to ask. I'm here to help.

Best regards,
Chen
<img width="1290" alt="Screenshot 2023-06-30 at 00 07 56" src="https://github.com/cafferychen777/ggpicrust2/assets/82987086/aece1792-e868-4dcc-9145-dac35a360999">
<img width="1221" alt="Screenshot 2023-06-30 at 00 08 16" src="https://github.com/cafferychen777/ggpicrust2/assets/82987086/e518d270-e239-485a-b3a7-86f87ee9a1c3">
<img width="1215" alt="Screenshot 2023-06-30 at 00 08 31" src="https://github.com/cafferychen777/ggpicrust2/assets/82987086/c88af54f-08bd-4970-812e-c28be78d6f53">

**Comment by Lacona** [comment]
OMG!!!! You sent the whole code!
That's amazing, thank you so much!
I'll try that and hope I don't have to bother you again.

Will you add multiple comparisons into your package? That would be so great.
________________________________
Von: Caffery Yang ***@***.***>
Gesendet: Donnerstag, 29. Juni 2023 11:08
An: cafferychen777/ggpicrust2 ***@***.***>
Cc: Andrea Pietruska ***@***.***>; Mention ***@***.***>
Betreff: [EXT] Re: [cafferychen777/ggpicrust2] ggpicrust2 error in levels (Issue #34)

CAUTION: Email Originated Outside of Auburn.

@Lacona<https://github.com/Lacona>

Dear Andrea,

Thank you for reaching out and for your patience. I understand that you have been exploring the ALDEx2 method and are having trouble figuring out how to perform multiple group comparisons. Unfortunately, the $results output does not provide the desired information.

To address this issue, you can try the following code snippet:

library(readr)
library(ggpicrust2)
library(tibble)
library(tidyverse)
library(ggprism)
library(patchwork)

# Load metadata as a tibble
metadata <- read_delim("/Users/apple/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/Lacona/Salmonella22_metadata_42R.tsv", delim = "\t", escape_double = FALSE, trim_ws = TRUE)

# Load KEGG pathway abundance
kegg_abundance <- ko2kegg_abundance("/Users/apple/Microbiome/ggpicrust2总/ggpicrust2测试/ggpicrust2_test/Lacona/pred_metagenome_unstrat (2).tsv")

# Perform pathway differential abundance analysis (DAA) using ALDEx2 method
daa_results_df <- pathway_daa(abundance = kegg_abundance, metadata = metadata, group = "treatment", daa_method = "ALDEx2", select = NULL, reference = NULL)

# Filter results for ALDEx2_Welch's t-test method
daa_sub_method_results_df <- daa_results_df[daa_results_df$method == "ALDEx2_Kruskal-Wallace test", ]

# Annotate pathway results using KO to KEGG conversion
daa_annotated_sub_method_results_df <- pathway_annotation(pathway = "KO", daa_results_df = daa_sub_method_results_df, ko_to_kegg = TRUE)

# Generate pathway error bar plot
pathway_errorbar(abundance = kegg_abundance, daa_results_df = daa_annotated_sub_method_results_df %>%
                        filter(!is.na(pathway_class)), Group = metadata$treatment, p_values_threshold = 0.05, order = "pathway_class", select = c("ko00561", "ko00310", "ko00604", "ko04973", "ko01051", "ko00300", "ko00591", "ko00253", "ko00380", "ko00625", "ko00627", "ko00270", "ko00941", "ko04910", "ko00363", "ko02010", "ko00361", "ko00362", "ko01040", "ko04626", "ko05020", "ko05146", "ko00051"), ko_to_kegg = TRUE, p_value_bar = FALSE, colors = NULL, x_lab = "pathway_name")

# Perform pathway PCA
pathway_pca(abundance = kegg_abundance, metadata = metadata, group = "treatment")

# Filter features with p-value < 0.05
feature_with_p_0.05 <- daa_annotated_sub_method_results_df %>% filter(p_adjust < 0.05) %>% filter(!is.na(pathway_class))

# Generate pathway heatmap
pathway_heatmap(abundance = kegg_abundance %>% filter(rownames(.) %in% feature_with_p_0.05$feature) %>% rownames_to_column("feature") %>% left_join(daa_annotated_sub_method_results_df %>% select(all_of(c("feature","pathway_name"))), by

 = "feature") %>% column_to_rownames("pathway_name") %>% select(-"feature"), metadata = metadata, group = "treatment")

Please ensure that you modify the file paths in the code snippet to match your actual data file locations. This code will help you perform multiple group comparisons using the ALDEx2 method and generate pathway error bar plots, pathway PCA plots, and pathway heatmaps based on your metadata and KEGG abundance data.

If you have any further questions or need additional assistance, please don't hesitate to ask. I'm here to help.

Best regards,
Chen
[Screenshot 2023-06-30 at 00 07 56]<https://user-images.githubusercontent.com/82987086/249836041-aece1792-e868-4dcc-9145-dac35a360999.png>
[Screenshot 2023-06-30 at 00 08 16]<https://user-images.githubusercontent.com/82987086/249836113-e518d270-e239-485a-b3a7-86f87ee9a1c3.png>
[Screenshot 2023-06-30 at 00 08 31]<https://user-images.githubusercontent.com/82987086/249836183-c88af54f-08bd-4970-812e-c28be78d6f53.png>

―

**Comment by cafferychen777** [comment]
Haha, no worries! Actually multiple comparisons have always been supported
in my package. 😂 Although your example didn't include multiple
comparisons, you can definitely use them. If you have any questions or need
assistance with implementing multiple comparisons in your code, feel free
to ask. I'm here to help!

**Comment by Lacona** [comment]
I'm very sorry, but I have to come back to you about the multiple group comparisons.
Your code worked perfectly fine and I got a nice heatmap, but I still struggle with identifying which groups are significantly different.
Usually the output of a post hoc test is something like this for all possible group comparisons:

groups  p-adj   sign
C - ST  0.00015 **
C - Ctrl        0.3     ns
...     ...     ...

The output of pathway_daa with ALDEx2 is:

feature method  group1  group 2 group3  group4  p-value
KO:     KW      C       CST     Ctrl    ST      0.005

How do I figure out if there is significant difference between the groups and the p-values for each comparison?

________________________________
Von: Caffery Yang ***@***.***>
Gesendet: Donnerstag, 29. Juni 2023 11:23
An: cafferychen777/ggpicrust2 ***@***.***>
Cc: Andrea Pietruska ***@***.***>; Mention ***@***.***>
Betreff: [EXT] Re: [cafferychen777/ggpicrust2] ggpicrust2 error in levels (Issue #34)

CAUTION: Email Originated Outside of Auburn.

Haha, no worries! Actually multiple comparisons have always been supported
in my package. 😂 Although your example didn't include multiple
comparisons, you can definitely use them. If you have any questions or need
assistance with implementing multiple comparisons in your code, feel free
to ask. I'm here to help!

**Comment by cafferychen777** [comment]
Dear,

I apologize for the inconvenience. To determine if there are significant
differences between the groups and obtain the p-values for each comparison,
I recommend following these steps:

1. Subset the dataset: Extract the two groups you want to compare from your
original dataset.

2. Run the pipeline again: Apply the necessary statistical tests or post
hoc analyses specifically on the subsetted data. This will allow you to
obtain the p-values and identify significant differences between the
selected groups.

By performing these steps, you will be able to focus on the specific group
comparisons and obtain the relevant statistical information. If you have
any further questions or need assistance with the process, please feel free
to ask.

Best regards,

**Comment by Lacona** [comment]
Thank you for your patience!
Well, how do I extract the treatment groups from my kegg_abundance, when there is no specification for treatments in the dataset? or from the daa_results where there are already all 4 groups mentioned for every KO? I can't see any chance of subsetting my data for the groups I want to compare.
________________________________
Von: Caffery Yang ***@***.***>
Gesendet: Freitag, 30. Juni 2023 03:41
An: cafferychen777/ggpicrust2 ***@***.***>
Cc: Andrea Pietruska ***@***.***>; Mention ***@***.***>
Betreff: [EXT] Re: [cafferychen777/ggpicrust2] ggpicrust2 error in levels (Issue #34)

CAUTION: Email Originated Outside of Auburn.

Dear,

I apologize for the inconvenience. To determine if there are significant
differences between the groups and obtain the p-values for each comparison,
I recommend following these steps:

1. Subset the dataset: Extract the two groups you want to compare from your
original dataset.

2. Run the pipeline again: Apply the necessary statistical tests or post
hoc analyses specifically on the subsetted data. This will allow you to
obtain the p-values and identify significant differences between the
selected groups.

By performing these steps, you will be able to focus on the specific group
comparisons and obtain the relevant statistical information. If you have
any further questions or need assistance with the process, please feel free
to ask.

Best regards,

**Comment by Lacona** [comment]
Maybe there is kind of a solurion in ALDEx2: you can get the expected clr value for each feature by setting the parameter: include.sample.summary = FALSE using aldex.effect()
But how can I apply that chunk of code to ggpicrust?
________________________________
Von: Andrea Pietruska ***@***.***>
Gesendet: Freitag, 30. Juni 2023 10:57
An: cafferychen777/ggpicrust2 ***@***.***>
Betreff: AW: [EXT] Re: [cafferychen777/ggpicrust2] ggpicrust2 error in levels (Issue #34)

Thank you for your patience!
Well, how do I extract the treatment groups from my kegg_abundance, when there is no specification for treatments in the dataset? or from the daa_results where there are already all 4 groups mentioned for every KO? I can't see any chance of subsetting my data for the groups I want to compare.
________________________________
Von: Caffery Yang ***@***.***>
Gesendet: Freitag, 30. Juni 2023 03:41
An: cafferychen777/ggpicrust2 ***@***.***>
Cc: Andrea Pietruska ***@***.***>; Mention ***@***.***>
Betreff: [EXT] Re: [cafferychen777/ggpicrust2] ggpicrust2 error in levels (Issue #34)

CAUTION: Email Originated Outside of Auburn.

Dear,

I apologize for the inconvenience. To determine if there are significant
differences between the groups and obtain the p-values for each comparison,
I recommend following these steps:

1. Subset the dataset: Extract the two groups you want to compare from your
original dataset.

2. Run the pipeline again: Apply the necessary statistical tests or post
hoc analyses specifically on the subsetted data. This will allow you to
obtain the p-values and identify significant differences between the
selected groups.

By performing these steps, you will be able to focus on the specific group
comparisons and obtain the relevant statistical information. If you have
any further questions or need assistance with the process, please feel free
to ask.

Best regards,

**Comment by cafferychen777** [comment]
Subsetting the dataset is a very easy thing. Maybe you guys should exercise your R skills instead of keeping telling something that is not related to ggpicrust.

**Comment by Lacona** [comment]
Well, thank you for your help!
________________________________
Von: Caffery Yang ***@***.***>
Gesendet: Samstag, 1. Juli 2023 00:28
An: cafferychen777/ggpicrust2 ***@***.***>
Cc: Andrea Pietruska ***@***.***>; Mention ***@***.***>
Betreff: [EXT] Re: [cafferychen777/ggpicrust2] ggpicrust2 error in levels (Issue #34)

CAUTION: Email Originated Outside of Auburn.

Subsetting the dataset is a very easy thing. Maybe you guys should exercise your R skills instead of keeping telling something that is not related to ggpicrust.
