### ISSUE TITLE
pathway_errorbar(): Can't add `e2` to a <ggplot> object.

### ISSUE THREAD

**Issue by Aristotle1992** [cafferychen777/ggpicrust2#42]
I ran the following lines of code and got an error while running thr pathway_errorbar code

# If you want to analyze KEGG pathway abundance instead of KO within the pathway, turn ko_to_kegg to TRUE.
# KEGG pathways typically have more explainable descriptions.

# Load metadata as a tibble
# data(metadata)
metadata <- read_delim("C:/Microbiome/picrust/Rhizo/check/rhizo_metadata.txt", delim = "\t", escape_double = FALSE, trim_ws = TRUE) 

# Load KEGG pathway abundance
# data(kegg_abundance)
kegg_abundance <- ko2kegg_abundance("C:/Microbiome/picrust/Rhizo/check/pred_metagenome_unstrat.tsv") 

# Perform pathway differential abundance analysis (DAA) using ALDEx2 method
# Please change group to "your_group_column" if you are not using example dataset
daa_results_df <- pathway_daa(abundance = kegg_abundance, metadata = metadata, group = "GDD", daa_method = "ALDEx2", select = NULL, reference = NULL) 

# Filter results for ALDEx2_Welch's t test method
# Please check the unique(daa_results_df$method) and choose one
daa_sub_method_results_df <- daa_results_df[daa_results_df$method == "ALDEx2_Wilcoxon rank test", ]

# Annotate pathway results using KO to KEGG conversion
daa_annotated_sub_method_results_df <- pathway_annotation(pathway = "KO", daa_results_df = daa_sub_method_results_df, ko_to_kegg = TRUE)

# Generate pathway error bar plot
# Please change Group to metadata$your_group_column if you are not using example dataset
p <- pathway_errorbar(abundance = kegg_abundance, daa_results_df = daa_annotated_sub_method_results_df, Group = metadata$GDD, 
                      p_values_threshold = 0.05, order = "pathway_class", select = daa_annotated_sub_method_results_df %>% arrange(p_adjust) %>% slice(1:20) %>% dplyr::select(feature) %>% pull(), 
                      ko_to_kegg = TRUE, p_value_bar = TRUE, colors = NULL, x_lab = "pathway_name")

I got hte following error while trying to generate the error bar plot

The following pathways are missing annotations and have been excluded: ko00281, ko00471, ko00472, ko00473
You can use the 'pathway_annotation' function to add annotations for these pathways.
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
Error in `ggplot_add()`:
! Can't add `e2` to a <ggplot> object.
Run `rlang::last_trace()` to see where the error occurred.

Please how can i resolve this?

**Comment by cafferychen777** [comment]
Hello @Aristotle1992 ,

It seems that you encountered an error while trying to generate the error bar plot in your R package ggpicrust2. The error message suggests that some packages dependencies are not loaded. To resolve this issue, please try loading the required package using the `library(patchwork)` command before generating the plot.

Here are the steps to follow:

1. Add the following line of code at the beginning of your script to load the necessary package:
   ```R
   library(patchwork)
   ```

2. Make sure to install the `patchwork` package if you haven't done so already. You can install it by running the following command:
   ```R
   install.packages("patchwork")
   ```

By loading the `patchwork` package, you should be able to resolve the error you encountered. If you face any further issues, please let me know.

Also, if you need any additional assistance or have any more questions, feel free to ask!

**Comment by Aristotle1992** [comment]
Thanks so much, I will try that out.

**Comment by Aristotle1992** [comment]
When i ran this last code:
p <- pathway_errorbar(abundance = kegg_abundance, daa_results_df = daa_annotated_sub_method_results_df, Group = metadata$GDD, 
                      p_values_threshold = 0.05, order = "pathway_class", select = daa_annotated_sub_method_results_df %>% arrange(p_adjust) %>% slice(1:20) %>% dplyr::select(feature) %>% pull(), 
                      ko_to_kegg = TRUE, p_value_bar = TRUE, colors = NULL, x_lab = "pathway_name")


p

I got these error again:

The following pathways are missing annotations and have been excluded: ko00281, ko00471, ko00472, ko00473
You can use the 'pathway_annotation' function to add annotations for these pathways.
Error: Index out of bounds
> p
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'guide_prism_offset_minor' of mode 'function' was not found

How can i resolve this.

**Comment by cafferychen777** [comment]
Hello @Aristotle1992 ,

You can check the https://github.com/cafferychen777/ggpicrust2#issue-2-guide_trainprism_offset_minor-error.

Best regards,
