### ISSUE TITLE
Question: how to extract mapping data in `pathway_errorbar`

### ISSUE THREAD

**Issue by Rainjie-afk** [cafferychen777/ggpicrust2#47]
Dear [cafferychen777](https://github.com/cafferychen777),

Thank you for this beautiful tool!

But I got a tiny question and want your help.

The question is how to extract data in `pathway_errorbar` step?

![image](https://github.com/cafferychen777/ggpicrust2/assets/68232446/104ef428-a452-4589-8242-ef456be3566e)

In particular, how to obtain the 'relatively abundance'  data in each group in the above figure.

Many thanks for your help!

**Comment by cafferychen777** [comment]
Hello @Rainjie-afk ,

You can use the similar code as follows

```
p <- pathway_errorbar()
p$data
```

Best regards,

**Comment by Rainjie-afk** [comment]
> Hello @Rainjie-afk ,
> 
> You can use the similar code as follows
> 
> ```
> p <- pathway_errorbar()
> p$data
> ```
> 
> Best regards,

Many thanks!
