### ISSUE TITLE
Error in `ggplot_add()`

### ISSUE THREAD

**Issue by luozhy88** [cafferychen777/ggpicrust2#5]
why?
<img width="987" alt="image" src="https://user-images.githubusercontent.com/94740863/229330001-1d671dae-2863-4140-a3c0-52151aa5bc03.png">

**Comment by luozhy88** [comment]
my R version 4.2.3

**Comment by cafferychen777** [comment]
I think you forgot to set p_values_bar = TRUE. Maybe when you encounter difficulties, you should firstly check the file. The CRAN file is the necessary thing for R learner

**Comment by cafferychen777** [comment]
Hello @luozhy88 ,

If you're still having problems, I suggest you run each individual function to solve the problem.

Best regards

**Comment by cafferychen777** [comment]
I ran the code same as you just now and did't find any problem.
<img width="715" alt="截屏2023-04-03 00 26 30" src="https://user-images.githubusercontent.com/82987086/229365859-5d5d2dc9-bd77-442d-800f-05122049f142.png">

**Comment by luozhy88** [comment]
I think you can update you git

**Comment by cafferychen777** [comment]
ggpicrust2() and pathway_errorbar() use different select parameter, you can check it in ggpicrust2() function. The select you use in ggpicrust2 won't be transfered to pathway_errorbar().
<img width="776" alt="截屏2023-04-03 21 47 41" src="https://user-images.githubusercontent.com/82987086/229528970-0ae7909c-edec-4981-97e5-a8ec52f138df.png">

**Comment by luozhy88** [comment]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/94740863/229533341-a89d0247-f0a6-4843-a02d-dc0f98d67f5c.png">

**Comment by luozhy88** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/94740863/229550833-7bb71a35-344d-4d6c-9a84-f36462e5136b.png">

**Comment by cafferychen777** [comment]
Please set select= NULL, because there are less than 30 statistically significant pathway in sample data.

发送自 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: luozhy88 ***@***.***>
发送时间: Monday, April 3, 2023 11:07:28 PM
收件人: cafferychen777/ggpicrust2 ***@***.***>
抄送: Caffery Yang ***@***.***>; Comment ***@***.***>
主题: Re: [cafferychen777/ggpicrust2] Error in `ggplot_add()` (Issue #5)


[image]<https://user-images.githubusercontent.com/94740863/229550833-7bb71a35-344d-4d6c-9a84-f36462e5136b.png>

―

**Comment by luozhy88** [comment]
it works! but it no show barplot.why?
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/94740863/229560769-0a700548-c0a8-4ee1-a7a7-ae5e13b1d1d5.png">

**Comment by luozhy88** [comment]
![Uploading image.png…]()

**Comment by luozhy88** [comment]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/94740863/229564410-29f297e5-35bd-4e73-9fe1-d054106bbb9d.png">

**Comment by cafferychen777** [comment]
I guess I know the Error in `ggplot_add()`:
! Can't add `e2` to a <ggplot> object. problem.

Please

```
library(patchwork)
```
