### ISSUE TITLE
compare_daa_results():  Maaslin2 method changed the names of the metacyc pathways, replacing a hyphen (-) with a dot (.)

### ISSUE THREAD

**Issue by dgkurt** [cafferychen777/ggpicrust2#51]
I had an issue with this function with my own data, but also with the sample dataset
```
library(ggpicrust2)
library(tidyverse)
data("metacyc_abundance")
data("metadata")

methods <- c("ALDEx2", "DESeq2", "edgeR")
daa_results_list <- lapply(methods, function(method) {
  pathway_daa(abundance = metacyc_abundance %>% column_to_rownames("pathway"), metadata = metadata, group = "Environment", daa_method = method)
})

method_names <- c("ALDEx2_Welch's t test","ALDEx2_Wilcoxon rank test","DESeq2", "edgeR")

comparison_results <- compare_daa_results(daa_results_list = daa_results_list, method_names = method_names)
```
**daa_results_list** contains three elements, but later **method_names** has four elements. As a result, comparison results provide a table where the method names do not correspond to the actual method used. The two variations of ALDEx2 ("ALDEx2_Welch's t test","ALDEx2_Wilcoxon rank test") are in the same pathway_daa result, however in the comparison table they are considered separately and wrongfully assigned to another method result

**Comment by cafferychen777** [comment]
Hello @dgkurt ,

Thank you for bringing this issue to our attention. After reviewing the code and the behavior of the `compare_daa_results` and `pathway_daa` functions, I can confirm that the code is working as intended.

If you look at the source code, you'll notice that each method in `daa_results_list` is correctly matched with the corresponding method name in `method_names`. The two variations of ALDEx2 ("ALDEx2_Welch's t test" and "ALDEx2_Wilcoxon rank test") are generated within the single `pathway_daa` result when using ALDEx2 as the `daa_method`. However, it's critical that the length of `method_names` matches the length of `daa_results_list` to ensure proper matching.

If you run the function with the correct setup, you should see that the method names in the comparison table correspond accurately to the actual methods used.

Please let me know if you have further questions or if there's anything else that requires clarification.

Best regards,
Chen YANG

**Comment by dgkurt** [comment]
Hello Chen, 

Good to hear that, and thanks for the quick answer! I copied the code above from the main page and had expected it to work.

Another small issue I had with this function is that the Maaslin2 method changed the names of the metacyc pathways, replacing a hyphen (-) with a dot (.). This caused comparisons including Maaslin2 to identify 0 common pathways.

**Comment by cafferychen777** [comment]
Hello @dgkurt ,

Thank you for bringing this issue to my attention. I have updated the example code to address the naming inconsistency caused by the Maaslin2 method.

You can try the updated code below:

```R
# Load necessary libraries
library(magrittr)
library(ggpicrust2)
library(tibble)

# Load example data
data("metacyc_abundance")
data("metadata")

# Run pathway_daa function for multiple methods
methods <- c("ALDEx2", "DESeq2", "edgeR","Maaslin2")
daa_results_list <- lapply(methods, function(method) {
  pathway_daa(
    abundance = metacyc_abundance %>% column_to_rownames("pathway"),
    metadata = metadata, 
    group = "Environment", 
    daa_method = method
  )
})

# Rename the list elements for easier identification
names(daa_results_list) <- methods

# Correct Maaslin2 feature names by replacing dots with hyphens
daa_results_list[["Maaslin2"]]$feature <- gsub("\\.", "-", daa_results_list[["Maaslin2"]]$feature)

# Compare results across different methods
comparison_results <- compare_daa_results(
  daa_results_list = daa_results_list,
  method_names = c("ALDEx2_Welch's t test","ALDEx2_Wilcoxon rank test","DESeq2", "edgeR", "Maaslin2")
)
```

This code should correct the naming inconsistency in Maaslin2 by replacing the dots with hyphens, allowing for proper comparison across different methods.

Please let me know if this resolves the issue for you or if you have any more questions.

Best regards,
Chen YANG

**Comment by dgkurt** [comment]
Thank you, Chen, the code works. Its only issue is the one you solved in the second post:
method_names should not include "ALDEx2_Welch's t test","ALDEx2_Wilcoxon rank test", and the comparison considers these two methods as one.
```
# Compare results across different methods
comparison_results <- compare_daa_results(
  daa_results_list = daa_results_list,
  method_names = c("ALDEx2_Welch's t test","ALDEx2_Wilcoxon rank test","DESeq2", "edgeR", "Maaslin2")
)
```
method_names for this code should be:
```
method_names = c("ALDEx2","DESeq2", "edgeR", "Maaslin2")
```

**Comment by cafferychen777** [comment]
Hello @dgkurt ,

Thank you for bringing this to my attention. You are absolutely correct about the `method_names` issue. I appreciate your feedback and have already updated the documentation to reflect this change.

If you have any more questions or suggestions, please feel free to reach out.

Best regards,
Chen YANG
