### ISSUE TITLE
ggpicrust Install Issues

### ISSUE THREAD

**Issue by ZellaD** [cafferychen777/ggpicrust2#55]
Hello! I really like the idea of ggpicrust. It looks like an efficient means of quickly analyzing picrust. Are there any plans to dockerize the package? I'm having an extremely hard time installing this package with endless dependency problems. I've tried just in R - just in Conda - in R and Conda and from renv::restore (renv.lock) all to no avail. For each dependency problem I install that package and try again and every time there is a different dependency problem.  I'm at the point of giving up and writing something myself to analyze picrust data. I've read the other two issue post on dependency problems none of which have been able to solve my problem. If this package was dockerized I think it would help not only me but future people looking to use this package.

**Comment by cafferychen777** [comment]
Hello @ZellaD,

Thank you for reaching out and for your kind words about ggpicrust2. I truly appreciate your feedback and understand the challenges you're facing with package dependencies.

I'm sorry for the inconvenience you've experienced. To address these issues, I've recently updated the `renv` files. I hope that the new `renv.lock` will make the installation process smoother and help resolve the dependency problems you've been encountering.

Moreover, I've noticed the redundancy in ggpicrust2's dependencies and recognize the need to streamline them. Rest assured, I'm working on refining this, and my goal for the next version is to reduce such redundancies to enhance the package's accessibility for our users.

Regarding dockerizing the package, it's a great suggestion. Docker containers can indeed simplify deployment by handling package dependencies, and it's something I will seriously consider for future updates to ensure easier accessibility for users like you.

In the meantime, please try installing with the updated `renv` files and let me know if you face any more issues. I'm here to help, and I'm dedicated to improving the usability of ggpicrust2 for everyone.

Best regards,

Chen YANG

**Comment by ZellaD** [comment]
Hi Chen YANG thank you for the updates. I was able to install the packages locally using a mix of conda and the the renv.lock file. For my pipeline development, I will try to dockerize the package. 

Cheers! 
ZellaD
