### ISSUE TITLE
ggpicrust2 input file

### ISSUE THREAD

**Issue by DaliBAmor** [cafferychen777/ggpicrust2#60]
Hello, I'm new in this field and look forward for some help 
Assuming that I want to execute this script : # Sample usage of the ko2kegg_abundance function
devtools::install_github('cafferychen777/ggpicrust2')

library(ggpicrust2)

# Assume that the KO abundance table is stored in a file named "ko_abundance.tsv"
ko_abundance_file <- "ko_abundance.tsv"

# Convert KO abundance to KEGG pathway abundance
kegg_abundance <- ko2kegg_abundance(file = ko_abundance_file)

# Alternatively, if the KO abundance data is already loaded as a data frame named "ko_abundance"
data("ko_abundance")
kegg_abundance <- ko2kegg_abundance(data = ko_abundance)

# The resulting kegg_abundance data frame can now be used for further analysis and visualization.
what does ko_abundance.tsv refers to in picrust2 pipeline that I have here ( what is the equivalent file name in this context ? ) : https://github.com/picrust/picrust2/wiki/PICRUSt2-Tutorial-(v2.5.2)

**Comment by cafferychen777** [comment]
Hello @DaliBAmor,

Based on the PICRUSt2 pipeline and the context you've provided, the file that corresponds to "ko_abundance.tsv" in your R script is likely "pred_metagenome_unstrat.csv". This file contains the predicted metagenome abundances, including the KEGG Orthology (KO) abundances. You can use this file as input for your subsequent analyses in the R script.

Best regards,
Chen YANG

**Comment by DaliBAmor** [comment]
@cafferychen777  thank you and how does metadata.txt file looks like please ?

**Comment by cafferychen777** [comment]
Hello @DaliBAmor,
 
For the structure and contents of the `metadata.txt` file, please refer to the documentation on my GitHub repository. Specifically, you can check [this section](https://github.com/cafferychen777/ggpicrust2#ggpicrust2) and also [this workflow](https://github.com/cafferychen777/ggpicrust2#if-an-error-occurs-with-ggpicrust2-please-use-the-following-workflow) for more details. Multiple datasets are available for download from there.

Best regards,
Chen YANG
