### ISSUE TITLE
Issue plotting LinDA results as heatmap when ko_to_kegg = FALSE

### ISSUE THREAD

**Issue by BiggusDickus666** [cafferychen777/ggpicrust2#84]
Hi,
I am trying to plot my PICRUSt output as a heatmap using the pathway_heatmap() function after performing LinDA analysis+Filtering+Annotation in a modular fashion. I disabled the conversion of KO function to KO pathway: all the example scripts seems to be well adapted to pathway analysis so I am having a hard time adapting the script for plotting the results when KO is not converted to KEGG. The error must be in the pathway_heatmap function. Here it is the code:

#RUN LINDA 

daa_results_df2LinDA <- pathway_daa(abundance = pred_metagenome_unstrat %>% column_to_rownames("X.NAME"), 
                               metadata = metadata2, 
                               group = "Plastic.Type", 
                               reference = "No plastic",
                               daa_method = "LinDA", 
                               select = NULL,
                               p.adjust = "fdr")

#FILTER LINDA  RESULTS

feature_with_p_0.05LINDA <- daa_results_df2LinDA %>% filter(p_adjust < 0.05)

# ANNOTATE LINDA RESULTS
annotated_daa_results_dfLINDA <- pathway_annotation( pathway = "KO",
  daa_results_df = daa_results_df2LinDA,
  ko_to_kegg = FALSE
)

#CREATE HEATMAP

heatmapLINDA <- pathway_heatmap(abundance = pred_metagenome_unstrat %>% 
    right_join(annotated_daa_results_dfLINDA %>% select(all_of(c("feature","description"))),
      by = c("feature")) %>% 
    filter(description %in% feature_with_p_0.05LINDA$feature) %>% 
    column_to_rownames("description"),
  metadata = metadata2, 
  group = "Plastic.Type"
)

Thank you very much in advance

**Comment by cafferychen777** [comment]
Hi there,

Thank you for sharing your code and detailing the issue you're facing with the `pathway_heatmap()` function in your PICRUSt analysis. To better assist you, it would be helpful if you could provide the dataset you're working with. This will allow me to understand the structure and format of your data, which is crucial for troubleshooting the issues you're encountering with the heatmap generation. You can attach the dataset files here, ensuring that any sensitive information is removed or anonymized. Looking forward to your response and assisting you further!

Best regards.

**Comment by BiggusDickus666** [comment]
Hi,
Here you are:
- PICRUSt output: unstratified KO (pred_metagenome_unstrat.csv)
- Metadata (metadata2.csv)

[metadata2.csv](https://github.com/cafferychen777/ggpicrust2/files/13918109/metadata2.csv)

[pred_metagenome_unstrat.csv](https://github.com/cafferychen777/ggpicrust2/files/13918112/pred_metagenome_unstrat.csv)

Thank you very much

**Comment by cafferychen777** [comment]
Dear @BiggusDickus666,

Thank you for reaching out with your question regarding the use of the `pathway_heatmap()` function in the context of PICRUSt output and LinDA analysis without converting KO function to KO pathway.

Based on the code snippet you provided, I have made a few adjustments to address the issue. Your approach is fundamentally sound, but the error might stem from handling the `description` column in the creation of the heatmap. The revised code below ensures that the `description` column is handled appropriately, especially when setting it as row names, which requires unique values.

Here is the revised code:

```R
library(readr)
library(ggpicrust2)
library(tibble)
library(tidyverse)
library(ggprism)
library(patchwork)
library(ggh4x)

# Load your data
pred_metagenome_unstrat <- read.delim("/path/to/your/pred_metagenome_unstrat.csv")
metadata2 <- read_delim("/path/to/your/metadata2.csv", 
                        delim = "\t", 
                        escape_double = FALSE, 
                        trim_ws = TRUE)

# Run LinDA
daa_results_df2LinDA <- pathway_daa(abundance = pred_metagenome_unstrat %>% column_to_rownames("X.NAME"), 
                                    metadata = metadata2, 
                                    group = "Plastic.Type", 
                                    reference = "No plastic",
                                    daa_method = "LinDA", 
                                    select = NULL,
                                    p.adjust = "fdr")

# Filter LinDA results
feature_with_p_0.05LINDA <- daa_results_df2LinDA %>%
  arrange(p_adjust) %>%
  slice_head(n = 30)

# Annotate LinDA results
annotated_daa_results_dfLINDA <- pathway_annotation(pathway = "KO",
                                                    daa_results_df = daa_results_df2LinDA,
                                                    ko_to_kegg = FALSE)

# Create Heatmap
heatmapLINDA <- pathway_heatmap(abundance = pred_metagenome_unstrat %>%
                                  column_to_rownames("X.NAME") %>%
                                  rownames_to_column("feature") %>%
                                  left_join(annotated_daa_results_dfLINDA %>% select(all_of(c("feature", "description"))),
                                            by = c("feature")) %>% 
                                  distinct() %>%
                                  filter(feature %in% feature_with_p_0.05LINDA$feature) %>%
                                  select(-all_of("feature")) %>%
                                  mutate(description = paste(description, row_number(), sep = "_")) %>%
                                  column_to_rownames("description"),
                                metadata = metadata2, 
                                group = "Plastic.Type")
```

Please replace `"/path/to/your/..."` with the actual paths to your `pred_metagenome_unstrat.csv` and `metadata2.csv` files. The revised code includes a step to create unique row names for the heatmap by appending row numbers to the `description` column. This should resolve the issue with non-unique row names.

If you encounter any further issues or have additional questions, please do not hesitate to reach out.

Best regards,
<img width="1589" alt="Screenshot 2024-01-16 at 19 35 54" src="https://github.com/cafferychen777/ggpicrust2/assets/82987086/44d0eace-6374-447b-88a1-eef75189d755">

Chen YANG

**Comment by BiggusDickus666** [comment]
Hi @cafferychen777 

Sorry for the late response. 
I just wanted to thank you for your amazing work and implication in solving the issue.

Victor
