### ISSUE TITLE
A bug in the function pathway_errorbar()

### ISSUE THREAD

**Issue by lixiaopi1985** [cafferychen777/ggpicrust2#9]
Hi,

Thank you for developing this package. 

As I ran through the workflow, I got an error with the funciton `pathway_errorbar() `
`Error in daa_results_df$pathway_name$description : 
  $ operator is invalid for atomic vectors`

The problem comes from this line of code in the function:
```
      if (is.null(daa_results_df$pathway_name)&is.null(daa_results_df$pathway_name$description)){
        message("Please use pathway_annotation to annotate the daa_results_df")
      }
```
precisely: `is.null(daa_results_df$pathway_name$description)`

The output of daa_results_df has a description column but not under pathway_name.

This will work if I change it to `is.null(daa_results_df$description)`.

Hope you can fix this.

Thanks,

**Comment by cafferychen777** [comment]
Hello,

Thank you for bringing this to my attention and I apologize for any
inconvenience it may have caused. I appreciate your feedback and I will
make the necessary changes to the pathway_errorbar() function to resolve
this issue.

You are correct, the line of code in question should be changed to
"is.null(daa_results_df$description)" to check for the presence of the
description column. Thank you for pointing that out.

If you have any further questions or concerns, please don't hesitate to let
me know.

Best regards, Chen YANG

Xiaoping Li ***@***.***>于2023年4月5日 周三00:03写道：
