### ISSUE TITLE
Error in `plot_theme()`: ! The `legend.text.align` theme element is not defined in the element hierarchy.

### ISSUE THREAD

**Issue by lananh-ngn** [cafferychen777/ggpicrust2#98]
Hello, thank you for developing this package.
**Describe the Bug**
I tried to run with the example data. It works after calling ggpicrust2() ("ggpicrust2 analysis completed"). However, when I call with `results_file_input[[1]]$plot`, I have the following error:
```
Error in `plot_theme()`:
! The `legend.text.align` theme element is not defined in the element hierarchy.
```

```r
data(ko_abundance)
data(metadata)
results_file_input <- ggpicrust2(data = ko_abundance,
                                 metadata = metadata,
                                 group = "Environment",
                                 pathway = "KO",
                                 daa_method = "LinDA",
                                 ko_to_kegg = TRUE,
                                 order = "pathway_class",
                                 p_values_bar = TRUE,
                                 x_lab = "pathway_name")
results_file_input[[1]]$plot
```

Similarly,
**Describe the Bug**
When I run with MetaCyc pathway, I get the following error:
```
Error in `guide_transform()`:
! <Guide> classes have been rewritten as <ggproto> classes.
The old S3 guide methods have been superseded..
```

```r
data(metacyc_abundance)
results_file_input <- ggpicrust2(data = metacyc_abundance,
                                 metadata = metadata,
                                 group = "Environment",
                                 pathway = "MetaCyc",
                                 daa_method = "LinDA",
                                 ko_to_kegg = FALSE,
                                 order = "group",
                                 p_values_bar = TRUE,
                                 x_lab = "description")
results_file_input[[1]]$plot
```

**Environment Information:**
 - Operating System: macOS 14.2.1 (23C71) (Apple M1)
 - R Version: R version 4.3.2
 - Package Version: ggpicrust2_1.7.3

Thank you in advance,
Best.

**EDIT**: Apparently, it comes from an incompatibility between ggplot2 and ggprism.

**Comment by lananh-ngn** [comment]
The solution for me was to downgrade to ggplot2 3.4.0.

**Comment by cafferychen777** [comment]
Hello Lan Anh,

Thank you for your message and for using ggpicrust2. I'm glad to hear that downgrading to ggplot2 version 3.4.0 resolved the issue you encountered. Your feedback is valuable, and I appreciate you sharing your solution with the community.

If you have any further questions or encounter any other issues, please feel free to reach out.

Best regards,
Chen YANG
